site_name: ACL Ethics
nav:
  - Home: index.md
  - Roles:
    - Authors: roles/authors.md
    - Instructors: roles/instructors.md
    - Organisers: roles/organisers.md
    - Researchers: roles/researchers.md
    - Reviewers: roles/reviewers.md
  - Tutorials:
        - tutorials/index.md
        - "Past tutorials":
          - tutorials/EACL_2023.md  
        - "Upcoming tutorials":
          - tutorials/ACL_2025.md
  - Resources:
        - resources/index.md
        - "Reading List":
          - resources/ethics-reading-list/index.md
          - "topic-single-file-header": resources/ethics-reading-list/single-file-header.md
          - "topic-biases": resources/ethics-reading-list/t-biases.md
          - "topic-crowdsourcing-issues": resources/ethics-reading-list/t-crowdsourcing-issues.md
          - "topic-data": resources/ethics-reading-list/t-data.md
          - "topic-dual-use": resources/ethics-reading-list/t-dual-use.md
          - "topic-environmental-impact": resources/ethics-reading-list/t-environmental-impact.md
          - "topic-evaluation": resources/ethics-reading-list/t-evaluation.md
          - "topic-general-resources": resources/ethics-reading-list/t-general-resources.md
          - "topic-language-diversity": resources/ethics-reading-list/t-language-diversity.md
          - "topic-model-issues": resources/ethics-reading-list/t-model-issues.md
          - "topic-uncategorized": resources/ethics-reading-list/t-uncategorized.md
          - "type-post": resources/ethics-reading-list/type-post.md
          - "type-preprint": resources/ethics-reading-list/type-preprint.md
          - "type-published": resources/ethics-reading-list/type-published.md
          - "type-report": resources/ethics-reading-list/type-report.md
  - Schedule: schedule.md
  - Committee: committee.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    # - navigation.prune
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

copyright: |
  &copy; 2023 <a href="https://github.com/acl-org/ethics-website"  target="_blank" rel="noopener">ACL Ethics Team</a>
