site_name: ACL Ethics
nav:
  - Home: index.md
  - Schedule: schedule.md
  - Committee: committee.md
  - Tutorials:
        - tutorials/index.md
        - "Past tutorials":
          - tutorials/EACL_2023.md  
        - "Upcoming tutorials":
          - tutorials/ACL_2025.md
  - Resources:
        - resources/index.md
        - "Reading List":
          - resources/ethics-reading-list/index.md
          - "single-file-header": resources/ethics-reading-list/single-file-header.md
          - "biases": resources/ethics-reading-list/t-biases.md
          - "crowdsourcing-issues": resources/ethics-reading-list/t-crowdsourcing-issues.md
          - "data": resources/ethics-reading-list/t-data.md
          - "dual-use": resources/ethics-reading-list/t-dual-use.md
          - "environmental-impact": resources/ethics-reading-list/t-environmental-impact.md
          - "evaluation": resources/ethics-reading-list/t-evaluation.md
          - "general-resources": resources/ethics-reading-list/t-general-resources.md
          - "language-diversity": resources/ethics-reading-list/t-language-diversity.md
          - "model-issues": resources/ethics-reading-list/t-model-issues.md
          - "uncategorized": resources/ethics-reading-list/t-uncategorized.md
          - "post": resources/ethics-reading-list/type-post.md
          - "preprint": resources/ethics-reading-list/type-preprint.md
          - "published": resources/ethics-reading-list/type-published.md
          - "report": resources/ethics-reading-list/type-report.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    # - navigation.prune
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

copyright: |
  &copy; 2023 <a href="https://github.com/acl-org/ethics-website"  target="_blank" rel="noopener">ACL Ethics Team</a>
