name: List Root Directory Files
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Echo repository info
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Create topic files in repository
        run: |
          # multi-word tags
          cd docs/resources/ethics-reading-list/
          for n in "general%20resources general-resources" "crowdsourcing%20issues crowdsourcing-issues" "dual%20use dual-use" "model%20issues model-issues" "language%20diversity language-diversity" "environmental%20impact environmental-impact"; do a=( $n ); grep t-${a[0]} index.md > x-${a[1]}.md; cat single-file-header.md x-${a[1]}.md > t-${a[1]}.md; done
          rm -f x-*
          # single word tag
          for n in biases data evaluation uncategorized; do grep t-$n index.md > x-$n.md; cat single-file-header.md x-$n.md > t-$n.md; done
          rm -f x-*

      - name: Setup git config
        run: |
          git config user.name "ACL Ethics Bibliography Actions Bot"
          git config user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -am "new local commit"
          git push origin

      - run: echo "🍏 This job's status is ${{ job.status }}."