name: Build Single Tag Versions
on: [push]
jobs: 
  Build-Single-Tag-Versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Create topic files in repository
        run: |
          # multi-word tags
          for n in "general%20resources general-resources" "crowdsourcing%20issues crowdsourcing-issues" "dual%20use dual-use" "model%20issues model-issues" "language%20diversity language-diversity" "environmental%20impact environmental-impact"; do a=( $n ); grep t-${a[0]} ${{ github.workspace }}/resources/ethics-reading-list/README.md > x-${a[1]}.md; cat single-file-header.md x-${a[1]}.md > t-${a[1]}.md; done
          rm -f x-*
          # single word tag
          for n in biases data evaluation uncategorized; do grep t-$n ${{ github.workspace }}/resources/ethics-reading-list/README.md > x-$n.md; cat single-file-header.md x-$n.md > t-$n.md; done
          rm -f x-*

      - name: Create type files in repository
        run: |
          for n in published preprint post report; do grep type-$n ${{ github.workspace }}/resources/ethics-reading-list/README.md > x-$n.md; cat single-file-header.md x-$n.md > type-$n.md; done
          rm -f x-*
          
      - name: setup git config
        run: |
          git config user.name "ACL Ethics Bibliography Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -am "new local commit"
          git push origin
      
      - run: echo "🍏 This job's status is ${{ job.status }}."
