name: List Root Directory Files
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # List files in the docs/resources/ethics-reading-list directory
      - name: List files in ethics-reading-list directory
        run: |
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          ls -la docs/resources/ethics-reading-list/
        
